### ISSUE TITLE
Ingest WV03_Pan_L1B granules for year 2014-2022 into Production

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#254]
Ingest 2014-2022 WV03_Pan_L1B

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/255
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/256
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/257
- [x] https://github.com/NASA-IMPACT/csdap-cumulus/issues/259
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/258
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/260
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/261
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/262
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/263
```

**Comment by krisstanton** [comment]
Cleaning up some of the tickets here.
I believe we completed all of these just before the Cumulus upgrade.  Closing this now.
