### ISSUE TITLE
SNYK Tickets Collection

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#383]
These are the Snyk tickets that came up during the past PI and are still active. 
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/396
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/400
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/401
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/404
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/403
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/397
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/402
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/398
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/405
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/426
- [ ] https://github.com/NASA-IMPACT/csdap-cumulus/issues/427
```
